# Generated by Django 4.2.29 on 2026-04-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_delivery_status_alter_internaltransfer_status_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockledger',
            new_name='ims_stock_l_movemen_b5ef07_idx',
            old_name='inventory_s_movemen_9743aa_idx',
        ),
        migrations.RenameIndex(
            model_name='stockledger',
            new_name='ims_stock_l_created_ca193a_idx',
            old_name='inventory_s_created_535aee_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='ims_customers',
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='ims_deliveries',
        ),
        migrations.AlterModelTable(
            name='deliveryitem',
            table='ims_delivery_items',
        ),
        migrations.AlterModelTable(
            name='internaltransfer',
            table='ims_internal_transfers',
        ),
        migrations.AlterModelTable(
            name='internaltransferitem',
            table='ims_internal_transfer_items',
        ),
        migrations.AlterModelTable(
            name='receipt',
            table='ims_receipts',
        ),
        migrations.AlterModelTable(
            name='receiptitem',
            table='ims_receipt_items',
        ),
        migrations.AlterModelTable(
            name='stockadjustment',
            table='ims_stock_adjustments',
        ),
        migrations.AlterModelTable(
            name='stockbalance',
            table='ims_stock_balances',
        ),
        migrations.AlterModelTable(
            name='stockledger',
            table='ims_stock_ledger_entries',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='ims_suppliers',
        ),
    ]
