# Generated by Django 4.2.29 on 2026-04-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='passwordresetotp',
            table='ims_password_reset_otps',
        ),
        migrations.AlterModelTable(
            name='user',
            table='ims_user_accounts',
        ),
    ]
