# Generated by Django 4.2.29 on 2026-04-07 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_alter_passwordresetotp_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLockoutState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('first_failure_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lock_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ims_login_lockout_states',
            },
        ),
    ]
