# Generated by Django 4.2.29 on 2026-04-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='ims_warehouse_locations',
        ),
        migrations.AlterModelTable(
            name='warehouse',
            table='ims_warehouses',
        ),
    ]
