# Generated by Django 4.2.29 on 2026-04-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='ims_product_categories',
        ),
        migrations.AlterModelTable(
            name='product',
            table='ims_products',
        ),
    ]
